var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                   o   o                                        ",
   "                                   x===x                                    xx  ",
   "  xx                               xxxxx  o o                                x  ",
   "  x                                                                          x  ",
   "  x                          xxxxxx      xxxxx            xxx     o        o x  ",
   "  x            o      oo                                                     x  ",
   "  x  @                                         % o                xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxx  xxxxxxx           xxxxxxxxxxxx===============xxxxxxxxx  ",
   "             x==x    x==x     x===========x          x=====xxxxxxxxxxx          ",
   "             x==x    x==x     x===========x          x=====x                    ",
   "             x==x    x==x     x===========x          x=====x                    ",
   "             xxxx    xxxx     xxxxxxxxxxxxx          xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                        oo                                                        ",
   "                                                                                                                  ",
   "                                                        xx                                                        ",
   "                                                   xx                                                             ",
   "                       o                     xx              o     o                                              ",
   "               o      xxx   xxx      xxx                                 oo                     xxx      o        ",
   "              xxx                                            xx    xx    xx    xx    xx     xx       xx        o  ",
   "  @    xxx                                                                                                 xxxxxxx",
   "xxxxx=============================================================================================================",
   "==================================================================================================================",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                               o                                                                         ",
   "                               x                                                                         ",
   "                              xx                        oo                                               ",
   "                               x                                                                         ",
   "                          xx   x   xxxxx               xx              xx              o          ooooooo",
   "                oo             x           oo      xx                  xx     xxx     xxx         xxxxxxx",
   "                     o         x           xx              o     o   xxxx================================",
   "         xxxxx      xxx        x                      &                xx================================",
   "       xx                      x       xx            xx    xx    xx    xx================================",
   "  @  xx                        x                                       xx================================",
   "xxxxx===================xxxxxxxxxxxxxxxxx==========================xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   ["                                                                                                     ",
   "                                                                                                      ",
   "                     o  x     x   xx    x    x      x  x  x  xxxxxxx  x      x o                      ",            
   "                    oo   x   x   x  x   x    x      x  x  x     x     x x    x oo                     ",
   "                   ooo    x x   x    x  x    x      x  x  x     x     x  x   x ooo                    ",
   "                  oooo     x    x    x  x    x      x  x  x     x     x   x  x oooo                   ",
   "                 ooooo     x    x    x  x    x      x  x  x     x     x    x x ooooo                  ",
   "                oooooo     x     x  x   x    x      x  x  x     x     x     xx oooooo                 ",
   "               ooooooo     x      xx    xxxxxx      xxxxxxx  xxxxxxx  x      x ooooooo                ",
   "                                                                                                      ",
   "                                                                                                      ",
   "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
